### ISSUE TITLE
Extreme lag for some reason???

### ISSUE THREAD

**Issue by ColonelKai** [Minecraft-Ships/ShipsForCore#23] opened 2020-11-08 10:32 UTC
I think this image should say it all.
![image](https://user-images.githubusercontent.com/59742334/98462639-d2465d00-21c6-11eb-9419-41c14435a8ba.png)

**Comment by mosemister** [comment] 2020-11-08 11:02
The "onPlayerInteractWithBlockEvent" is when you hit any of the signs. That I can work out, however I know you have opened a issue about lag in that respect. 

I am confused with the player quit event which seems to be main source of lag. The issue is Ships itself doesnt listen to the quit event, however the translation layer does. I will take a look into the player quit event. Do you have any ships addons?

**Comment by ColonelKai** [comment] 2020-11-08 11:53
Okay lmao, I don't have any ship addons btw, I wanted the damage one but it was outdated :(

**Comment by mosemister** [comment] 2020-11-08 12:38
Yeah sorry about Ships damage. The developer is really busy these days. 

Still getting round to fixing the player leave lag. Bare with me :)

**Comment by ColonelKai** [comment] 2020-11-08 13:43
Lol, it's completely okay, I understand the struggle of doing something like this for free.

I'd donate but I am as broke as an amateur student can be.

Overall your plugin is really good quality and well done, and you are still working on it, so ill report as many bugs as i can. We do catch a lot of bugs given  that we are a somewhat nicely sized server, around 2-3 people at the mornings and up to 15 at evenings. Ill try my best to help.

**Comment by mosemister** [comment] 2020-11-08 13:55
Thanks for understanding. As for donating don't worry, im more then happy seeing that your getting use out of it. The bug reports are just a bonus.

**Comment by mosemister** [comment] 2020-11-09 16:47
The player quit event issue should be fixed in beta 9.1. Please confirm and close when its approved

**Comment by ColonelKai** [comment] 2020-11-10 09:19
aight, ill return to you

**Comment by ColonelKai** [comment] 2020-11-10 09:22
Where can i get 9.1?

**Comment by mosemister** [comment] 2020-11-10 09:36
```Please confirm and close when its approved```

Its still awaiting for approval ;) 

(it sometimes happens when im sleeping, I have no control over it so I sent that message in hopes it would be approved by the time you see it. Sorry for the confusion.

**Comment by mosemister** [comment] 2020-11-11 11:16
Its now approved

**Comment by mosemister** [comment] 2020-11-29 23:43
Closed due to a lack of response after the update was approved. Assuming all changes have been fixed.

**Closed by mosemister** 2020-11-29 23:43 UTC
Labels: bug
