### ISSUE TITLE
Crash + console errors

### ISSUE THREAD

**Issue by Insidi0usAngel** [Minecraft-Ships/ShipsForCore#83] opened 2022-05-28 10:19 UTC
Added ships to my plugins 2 days ago. All the Ram was sucked out of my server until it would crash.  The error started whilst doing some mining and whilst opening storage plugins.  In console logs I also saw messages from Multiverse core that all my worlds were corrupted! On removing ships plugin, there are no more problems mining (using custom enchants that multi block break) or with the storage plugins that have been used for months.  All console messages from multiverse core about the worlds being corrupted also stopped.  In cosole there were over 800,000 lines of errors regarding ships so I have copied a chunk of the main error messages as follows:

https://pastebin.com/vdUjX8nw

**To Reproduce**
1. Minecraft version (eg. 1.18.2)
2. Platform: Paper version git-Paper-"3f7fbe3" (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: 3f7fbe3)
3. Ships v6.0.0

**Log**
If applicable, add your server log to help explain your problem.
[2022-05-27-3.log.gz](https://github.com/Minecraft-Ships/ShipsForCore/files/8790943/2022-05-27-3.log.gz)

There were 7 server logs yesterday, but this log 3 shows the issues described above: multiverse core corruption messages + server ram being fully used above available 8GB + ships console errors.  Hope this helps for a fix because world corruption messages are terrifying but I would love to use this plugin if it can be compatible with my server/other plugins.

**Comment by mosemister** [comment] 2022-05-28 12:47
Hi @Insidi0usAngel 

The issue is known and I'm working on a fix, however if you want to use the plugin now, there is a work around. 

``/ships config set config advanced.block.finder Ships_Six`` 

I'm currently on mobile so please use the in game suggestions to help. You want to chose the one ending in Ships six (and not "ships six async"). This work around means the calculation to work out a ship will be slower (however if you only have small ships, then it's unnoticable)

If you want to know, it's cause by a memory leak in the async ships 6 block finder, the others are fine to use but all have there own issues

**Comment by Insidi0usAngel** [comment] 2022-05-29 10:56
Thanks, I tried that and it fixed all console errors and the other issues, except for lag when mining etc is still there. As I had only just installed plugin recently there are no ships made yet.  It is great to here though that you already know about the issues and are working on fixing them.  I have a lot of other projects to build/plugins to work on so I will just wait patiently until there are new releases :)  Everyone who plays my server is very excited about the potential ships plugin offers - moving ships without slime blocks and pistons and without texture packs, that actually works kind of takes vanilla minecraft to another level and its something everyone has always wanted to do in minecraft for years!  So I look forward to development of the plugin!!  Good luck!!!!

**Comment by mosemister** [comment] 2022-05-29 11:03
Thanks. This plugin has been around since 2012 so you have been able to do it for a decade ;)
But thank you, not many people thank the developer so thanks for that. 

I forgot to mention to restart the server (if you haven't already) after applying the command as that remove the memory leak from leaking more. So hopefully that fixes the lag that you get from mining. 

The issue I have currently is while I understand where the issue is and I think why it's happening. I've also got to work out how to prevent it. But hopefully I work it out soon

**Comment by mosemister** [comment] 2022-06-14 16:33
I have fixed it in ships 14.5. just awaiting approval

**Comment by Insidi0usAngel** [comment] 2022-08-03 23:34
Sorry I was a bit scared of trying again with this after updating my server to 1.19 etc.  But tonight is the night I added it back onto my server and I can report everything is working for me flawlessly now.  There is no lag or crashes, people can mine etc without lag.  We have the very first ship sailing away happily too!  It is actually a swan, so there you go - swan boats that require no peddling :)

**Comment by mosemister** [comment] 2022-08-04 06:09
So we have found that it's not completely fixed, there is a situation where it can happen. This is fixed in the Dev versions, however it has caused the boss bar to go odd, so fixing that before releasing the update. 

Good to know your happy though

**Comment by Insidi0usAngel** [comment] 2022-08-06 19:44
Ok maybe I was a bit too soon to close the issue... recently I took on a new project - add a new world with custom terrain, by nature that's going to be server resource intensive so whilst loading terrain in new world suddenly my server crashed.... the console was filled with the following:
[Server] Startup[19:39:56 ERROR]: Nag author: '<NoAuthorGiven>' of 'Ships' about the following: This plugin is not properly shutting down its async tasks when it is being shut down. This task may throw errors during the final shutdown logs and might not complete before process dies.
So I don't know if this is 100% a ships issue or if it was partly because i was doing some intensive RAM usage with the new custom world....

**Comment by mosemister** [comment] 2022-08-06 20:26
I'm aware of the error messages, fixing them up in the Dev versions. It's a little complex to fix. 

But I can guarantee you it's nothing to worry about. All the async stuff is reading data and not modifying files

**Comment by Insidi0usAngel** [comment] 2022-08-06 20:56
After deleting the custom terrain world I tried shutting down and restarting server a few times and did not get any error messages at all, so for me at least the issues only occur when server crashes through other plugins taking too many resources/causing a crash which then means nothing shuts down in the proper order.  Is it worth downloading a dev build or given that this plugin is not causing any real problems better to just wait until next official build is out?

**Comment by mosemister** [comment] 2022-08-06 21:08
Currently there is a issue with the Dev build where the boss bar stays. If you have the boss bar option disabled then it's not a issue, however I haven't fully tested it for other issues .... So some may be found. 

It's got some pretty serious changes to the translation layer, so I wouldn't be surprised if something else broke. 

So I would stay on the current version unless your experiencing performance issues

**Comment by mosemister** [comment] 2022-08-10 21:25
Fully fixed in beta 15

**Closed by mosemister** 2022-08-10 21:25 UTC
Labels: bug, Verified Bug
