### ISSUE TITLE
random bedrock bug

### ISSUE THREAD

**Issue by TheKr1szTEN** [Minecraft-Ships/ShipsForCore#11] opened 2020-06-30 10:35 UTC
https://cdn.discordapp.com/attachments/493469532363554818/727472044866011167/unknown.png

Randomly

Oh, and when we break a sign, the bosbar still in the top

**Comment by TheKr1szTEN** [comment] 2020-06-30 10:36
[10:36:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH  - git-Paper-374 (MC: 1.15.2) ---
[10:36:33 ERROR]: The server has not responded for 35 seconds! Creating thread dump
[10:36:33 ERROR]: ------------------------------
[10:36:33 ERROR]: Server thread dump (Look for plugins here before reporting to Paper!):
[10:36:33 ERROR]: ------------------------------
[10:36:33 ERROR]: Current Thread: Server thread
[10:36:33 ERROR]:       PID: 20 | Suspended: false | Native: false | State: RUNNABLE
[10:36:33 ERROR]:       Stack:
[10:36:33 ERROR]:               java.base@11.0.7/java.lang.Long.toString(Long.java:474)
[10:36:33 ERROR]:               java.base@11.0.7/java.lang.Long.toString(Long.java:129)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigInteger.smallToString(BigInteger.java:3977)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigInteger.toString(BigInteger.java:3939)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigInteger.toString(BigInteger.java:4100)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigDecimal.layoutChars(BigDecimal.java:3836)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigDecimal.toString(BigDecimal.java:3231)
[10:36:33 ERROR]:               java.base@11.0.7/java.math.BigDecimal.doubleValue(BigDecimal.java:3663)
[10:36:33 ERROR]:               org.core.vector.types.Vector3Double.getZ(Vector3Double.java:35)
[10:36:33 ERROR]:               org.core.world.Extent.getPosition(Extent.java:36)
[10:36:33 ERROR]:               org.core.world.position.impl.sync.SyncPosition.getRelative(SyncPosition.java:50)
[10:36:33 ERROR]:               org.core.world.position.impl.sync.SyncExactPosition.getRelative(SyncExactPosition.java:29)
[10:36:33 ERROR]:               org.core.entity.Entity.getAttachedTo(Entity.java:302)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel.lambda$getEntities$4(Vessel.java:80)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel$$Lambda$5633/0x0000000841bd8040.test(Unknown Source)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.HashMap$KeySpliterator.tryAdvance(HashMap.java:1624)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel.lambda$getEntities$5(Vessel.java:80)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel$$Lambda$5632/0x0000000841bc9440.test(Unknown Source)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1603)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel.getEntities(Vessel.java:81)
[10:36:33 ERROR]:               org.ships.vessel.common.types.Vessel.getEntities(Vessel.java:66)
[10:36:33 ERROR]:               org.ships.vessel.sign.WheelSign.lambda$onVesselRotate$5(WheelSign.java:137)
[10:36:33 ERROR]:               org.ships.vessel.sign.WheelSign$$Lambda$5794/0x0000000841c32040.accept(Unknown Source)
[10:36:33 ERROR]:               java.base@11.0.7/java.util.Optional.ifPresent(Optional.java:183)
[10:36:33 ERROR]:               org.ships.vessel.sign.WheelSign.onVesselRotate(WheelSign.java:135)
[10:36:33 ERROR]:               org.ships.vessel.sign.WheelSign.access$000(WheelSign.java:29)
[10:36:33 ERROR]:               org.ships.vessel.sign.WheelSign$1.onStructureUpdate(WheelSign.java:88)
[10:36:33 ERROR]:               org.ships.vessel.common.loader.ShipsOvertimeUpdateBlockLoader$OvertimeRunnable.onShipsStructureUpdated(ShipsOvertimeUpdateBlockLoader.java:42)
[10:36:33 ERROR]:               org.ships.algorthum.blockfinder.Ships6BlockFinder$Overtime.lambda$new$0(Ships6BlockFinder.java:95)
[10:36:33 ERROR]:               org.ships.algorthum.blockfinder.Ships6BlockFinder$Overtime$$Lambda$5008/0x0000000841a2f840.run(Unknown Source)
[10:36:33 ERROR]:               org.ships.implementation.bukkit.scheduler.BScheduler$RunAfterScheduler.run(BScheduler.java:16)
[10:36:33 ERROR]:               app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99)
[10:36:33 ERROR]:               app//org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468)
[10:36:33 ERROR]:               app//net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1264)
[10:36:33 ERROR]:               app//net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[10:36:33 ERROR]:               app//net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1181)
[10:36:33 ERROR]:               app//net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970)
[10:36:33 ERROR]:               java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
[10:36:33 ERROR]: ------------------------------
[10:36:33 ERROR]: --- DO NOT REPORT THIS TO PAPER - THIS IS NOT A BUG OR A CRASH ---
[10:36:33 ERROR]: ------------------------------

**Comment by TheKr1szTEN** [comment] 2020-06-30 10:37
https://media.discordapp.net/attachments/493469532363554818/727472680890269696/unknown.png?width=1170&height=658

**Comment by mosemister** [comment] 2020-06-30 10:56
Hi, so the bedrock issue there is caused by the message of "No licence sign", the bedrock will only show you for, it is not on the actual server, it should only last 10 seconds, however if Ships crashes during the bedrock change then it will not change back for you unless you reload your texture pack.

As for the crash, thats a known issue, it is caused by Ships tracking a very large ship and attempting to find all entities on the ship, in the next update this issue should be fixed, in the mean time you will need to use smaller ships, based upon the bedrock in your image, it looks like Ships is detecting part of your land as the ship, making the "ship" much larger then it actually is. 

As for the bars, they stay due to ships not being able to complete the action. I belive all three issues you posted are related to the ship just being too large.

**Comment by mosemister** [comment] 2020-07-18 08:20
Closed due to inactivity

**Closed by mosemister** 2020-07-18 08:20 UTC
Labels: bug
